### ISSUE TITLE
py3 compatibility: iteritems

### ISSUE THREAD

**Issue by jonozzz** [erjac77/ansible-common-f5#4]
I tried running a few plays in a python3.6 venv and it kept complaining about iteritems. This is just one occurrence, but there are others including in the ansible-module-f5bigip module.

I think you should switch to just 'items' or use six.

https://github.com/erjac77/ansible-common-f5/blob/dcb3d904f72bbaaf442dd95b386bcd88da8d5939/ansible_common_f5/f5_base.py#L223

**Comment by erjac77** [comment]
@jonozzz , If you can check the updated code to make sure that it addresses the Py3 compatibility issue, I'd appreciate it.

**Comment by jonozzz** [comment]
:+1:
